name: Pytest BDD Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Install Playwright Browsers
    - name: Install Playwright Browsers
      run: |
        python -m playwright install --with-deps

    # Step 5: Create reports directory
    - name: Create reports directory
      run: mkdir -p reports

    # Step 6: Run Pytest-BDD tests
    - name: Run Pytest-BDD tests
      run: |
        pytest --gherkin-terminal-reporter --log-cli-level=INFO --html=reports/report.html --self-contained-html

    # Step 7: Upload test videos
    - name: Upload test videos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-videos
        path: videos/
        retention-days: 30

    # Step 8: Upload pytest-bdd report
    - name: Upload pytest-bdd report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-bdd-report
        path: reports/report.html
        retention-days: 30
